from __future__ import annotations

DEMO_MODE = True
TICK_INTERVAL_SECONDS = 0.05
DECAY_HALF_LIFE_TICKS = 60

NODE_COUNT = 20
DETECTORS_PER_NODE = 50

DANGER_THRESHOLD = 0.4
GOSSIP_THRESHOLD = 0.5
CONSENSUS_THRESHOLD = 0.5
CONSENSUS_NEIGHBOUR_COUNT = 2
CONSENSUS_WINDOW_TICKS = 50

DANGER_SENSITIVITY_TICKS = 120
GOSSIP_MAX_HOPS = 3

APT_TARGET_COUNT = 5
APT_SUSPICION_FLOOR = 0.22

MEMORY_DISTANCE_THRESHOLD = 0.2
